name: Build static site, deploy, check links

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: yantantether/muffet-action@main
        if: contains(github.ref, 'main')
        with:
          url: "https://nhsbsa.github.io/nhsbsa-digital-playbook"
          buffer_size: 8192
          exclude: "assets.nhs.uk/$ nhsbsauk.sharepoint.com www.baeldung.com docs.aws.amazon.com/ec2 www.pluralsight.com dps-gitlab.service.nhsbsa www.npmjs.com nhsbsa-digital-playbook/issues/new owasp.org/www-project-secure-headers"
          max_connections: 20
          max_connections_per_host: 2
          timeout: 30
          header: "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0"

