name: Build Eleventy

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies & build
        run: |
          npm ci
          npm run build          

      - name: Deploy GH Pages
        if: contains(github.ref, 'main')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site/nhsbsa-digital-playbook
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude_assets: '_redirects'

      - name: Deploy Netlify
        if: contains(github.ref, 'develop')
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: netlify
          github_token: ${{ secrets.GITHUB_TOKEN }}
